### ISSUE TITLE
Memory leak if mass table can't be opened

### ISSUE THREAD

**Issue by warr** [VinzenzBildstein/TRexGeant4#6]
In Isotopes.cc there's an open followed by a loop, which reads and adds to a vector. However, if the open fails, it is neither bad() nor eof() but simply !is_open(). So the loop becomes a tight infinite loop calling std::vector::push_back until the OutOfMemory killer intervenes. You could put something like:

if (!massFile.is_open()) throw std::invalid_argument("Unable to open mass file");

after the open.

**Comment by VinzenzBildstein** [comment]
Thanks for finding that bug. I fixed it the way you suggested.
